### ISSUE TITLE
Checkpoints are keep appending to the previous executions.

### ISSUE THREAD

**Issue by Jagdish-J-P** [Janiaje/laravel-benchmark#2]
**Checkpoints are keep appending to the previously executed script. If I execute script multiple times it is not showing checkpoints created for that particular script.**

**Expected behavior**
Either package should add function to clear checkpoints or when we call function getCheckpoints or getElapsedTime there should be arguments to auto clear checkpoints after returning result.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser console
 - Version Windows 11

**Comment by Janiaje** [comment]
Hi @Jagdish-J-P,

Thank you for opening this ticket :)

By default, you can create your separate `Benchmark` object (`$myBenchmark = new Benchmark`) and you can collect the checkpoints as you want.

Just in case, I added a grouping functionality in the #3 merge request.

I created the @Janiaje/laravel-benchmark#v2.0.0 version, which you can now download from composer  :)

Let me know if you have any other suggestions / future request :)
